version: 0.2
env:
  variables:
    REPO: "753392824297.dkr.ecr.us-east-1.amazonaws.com/hello-world-demo" 
phases:
  pre_build:
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
      - TAG=$(echo $CODEBUILD_SOURCE_VERSION | head -c 8)
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo $TAG
      - echo $REPO
      - docker build --tag $REPO:$TAG .
  post_build:
    commands:
      - docker push $REPO:$TAG